name: otpify_example
description: Example app to demonstrate Otpify package.
publish_to: 'none'  # Keep this to prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  otpify:
    path: ../  # This points to your local Otpify package folder
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/example.gif  # Add this line to include your GIF file
